# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.TextField()),
                ('linenos', models.BooleanField(default=False)),
                ('highlighted', models.TextField()),
                ('poster_title', models.CharField(max_length=30)),
                ('poster_img', models.ImageField(upload_to='poster/post_img/')),
                ('genre', models.CharField(max_length=30)),
                ('grade', models.IntegerField(choices=[(0, '전체관람가'), (12, '12세이상 관람가'), (15, '15세이상 관람가'), (18, '청소년 관람불가')], default=1, help_text='관람 선택')),
                ('fee', models.IntegerField()),
                ('location', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=100)),
                ('thumbnail_img_1', models.ImageField(upload_to='poster/thumbnail_1/')),
                ('thumbnail_img_2', models.ImageField(upload_to='poster/thumbnail_2/')),
                ('time', models.TimeField(help_text='HH:MM')),
                ('date_start', models.DateField(help_text='YYYY-MM-DD')),
                ('date_end', models.DateField(help_text='YYYY-MM-DD')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
